openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/documents/:
    get:
      operationId: listTextDocuments
      description: ''
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                type: object
                required:
                - count
                - results
                properties:
                  count:
                    type: integer
                    example: 123
                  next:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?offset=400&limit=100
                  previous:
                    type: string
                    nullable: true
                    format: uri
                    example: http://api.example.org/accounts/?offset=200&limit=100
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/TextDocument'
          description: ''
      tags:
      - api
    post:
      operationId: createTextDocument
      description: ''
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TextDocument'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextDocument'
          description: ''
      tags:
      - api
  /api/v1/documents/{id}/:
    get:
      operationId: retrieveTextDocument
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this text document.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextDocument'
          description: ''
      tags:
      - api
    put:
      operationId: updateTextDocument
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this text document.
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TextDocument'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextDocument'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateTextDocument
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this text document.
        schema:
          type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TextDocument'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextDocument'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyTextDocument
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this text document.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/v1/documents/{id}/chunks/:
    get:
      operationId: chunksTextDocument
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this text document.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextDocument'
          description: ''
      tags:
      - api
  /api/v1/labels/:
    get:
      operationId: listLabels
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Label'
          description: ''
      tags:
      - api
    post:
      operationId: createLabel
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Label'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Label'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Label'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Label'
          description: ''
      tags:
      - api
  /api/v1/labels/{id}/:
    get:
      operationId: retrieveLabel
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this label.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Label'
          description: ''
      tags:
      - api
    put:
      operationId: updateLabel
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this label.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Label'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Label'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Label'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Label'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateLabel
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this label.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Label'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Label'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Label'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Label'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyLabel
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this label.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/v1/annotations/:
    get:
      operationId: listAnnotations
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Annotation'
          description: ''
      tags:
      - api
    post:
      operationId: createAnnotation
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Annotation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Annotation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Annotation'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Annotation'
          description: ''
      tags:
      - api
  /api/v1/annotations/{id}/:
    get:
      operationId: retrieveAnnotation
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this annotation.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Annotation'
          description: ''
      tags:
      - api
    put:
      operationId: updateAnnotation
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this annotation.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Annotation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Annotation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Annotation'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Annotation'
          description: ''
      tags:
      - api
    patch:
      operationId: partialUpdateAnnotation
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this annotation.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Annotation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Annotation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Annotation'
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Annotation'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyAnnotation
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this annotation.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/v1/documents/upload/:
    post:
      operationId: uploadFileTextDocument
      description: ''
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TextDocument'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TextDocument'
          description: ''
      tags:
      - api
  /api/v1/jwt/create/:
    post:
      operationId: createTokenObtainPair
      description: 'Takes a set of user credentials and returns an access and refresh
        JSON web

        token pair to prove the authentication of those credentials.'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
      tags:
      - api
  /api/v1/jwt/refresh/:
    post:
      operationId: createTokenRefresh
      description: 'Takes a refresh type JSON web token and returns an access type
        JSON web

        token if the refresh token is valid.'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
      tags:
      - api
  /api/v1/jwt/verify/:
    post:
      operationId: createTokenVerify
      description: 'Takes a token and indicates if it is valid.  This view provides
        no

        information about a token''s fitness for a particular use.'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenVerify'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenVerify'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenVerify'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenVerify'
          description: ''
      tags:
      - api
components:
  schemas:
    TextDocument:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        user:
          type: string
          readOnly: true
        title:
          type: string
          maxLength: 255
        content:
          type: string
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - content
    Label:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
          maxLength: 100
        color:
          type: string
          maxLength: 7
      required:
      - name
    Annotation:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        document:
          type: integer
        label:
          type: integer
        start:
          type: integer
          maximum: 9223372036854775807
          format: int64
          minimum: 0
        end:
          type: integer
          maximum: 9223372036854775807
          format: int64
          minimum: 0
        text:
          type: string
          readOnly: true
        created_at:
          type: string
          format: date-time
          readOnly: true
      required:
      - document
      - label
      - start
      - end
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
      required:
      - username
      - password
    TokenRefresh:
      type: object
      properties:
        refresh:
          type: string
        access:
          type: string
          readOnly: true
      required:
      - refresh
    TokenVerify:
      type: object
      properties:
        token:
          type: string
          writeOnly: true
      required:
      - token
